# Generated by Django 2.0.3 on 2018-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'is_complete'],
            },
        ),
    ]
